
import type { Metadata } from "next";
import { Geist, Geist_Mono,Space_Grotesk } from "next/font/google";
import "../globals.css";
import NavBar from "@/app/components/nav-bar";
import Provider from "@/app/provider";


const spaceGrotesk = Space_Grotesk({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${spaceGrotesk.variable}
         text-white
         antialiased
         h-full
         md:px-3.5
         xl:px-56
         bg-gradient-to-b from-[#101216] to-[#0F1014]`}
      >
        <Provider>
          <NavBar />
          {children}
        </Provider>
      </body>
    </html>

  );
}
