
import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "../../../globals.css";
import Provider from "@/app/provider";
import { ReactLenis } from "@/app/lib/lenis";
import { SidebarProvider, SidebarTrigger } from "@/app/components/ui/sidebar";
import { AppSidebar } from "@/app/components/dashboard/side-navbar";
import DashboardNavBar from "@/app/components/dashboard/nav-bar";
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../../components/ui/tabs'

const spaceGrotesk = Space_Grotesk({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default async function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
            <ReactLenis root options={{ lerp: 0.8, duration: 1.5 }}>
                <body
                    className={`
                        ${spaceGrotesk.className}
                        relative top-0 h-full w-full bg-white px-4 sm:px-6 md:px-8
                        max-w-full sm:max-w-[540px] md:max-w-[720px]
                        lg:max-w-[960px] xl:max-w-[1280px] mx-auto
                    `}
                >
                    <Provider>
                        <div className="pointer-events-none absolute right-0 top-0 h-[500px] w-[500px] -translate-x-[30%] translate-y-[20%] bg-green/90 rounded-full  opacity-50 blur-[80px]" />
                        {/* bg-[rgba(173,109,244,0.5)] */}

                        <Tabs defaultValue="dashboard" className="h-full w-full">
                            <DashboardNavBar />
                            {children}
                        </Tabs>
                    </Provider>
                </body>
            </ReactLenis>
        </html >
    );

}




